import Foundation

/// Road-following geometry for drawn bus rides: a faithful port of web/js/map/geometry.js `alongShape`
/// (same constants, same candidate rules, same fallbacks). Tested with the cases of web/tests/map-geometry.js
/// plus a golden file generated by the JavaScript on real routes (GeometryTests).
public enum Geometry {
    static let earthRadius = 6_371_000.0
    static let rad = Double.pi / 180
    /// Stops farther than this from every shape line are not on the shape: use the fallback.
    static let maxOffM = 200.0
    /// Shapes whose ends are this close are treated as closed loops.
    static let closedM = 80.0

    /// The valid points of a list (the web's `normLatLngs`).
    public static func norm(_ list: [LatLon]?) -> [LatLon] { (list ?? []).filter(\.isValid) }

    /// Great-circle distance in meters; infinity when a point is invalid (geometry.js `distM`).
    public static func distM(_ a: LatLon, _ b: LatLon) -> Double {
        guard a.isValid, b.isValid else { return .infinity }
        return Geo.hav(a, b)
    }

    /// Total length of a polyline in meters.
    public static func pathLength(_ line: [LatLon]) -> Double {
        var s = 0.0
        if line.count > 1 { for i in 1..<line.count { s += distM(line[i - 1], line[i]) } }
        return s
    }

    /// Cumulative distance at each vertex.
    static func cumulative(_ line: [LatLon]) -> [Double] {
        var cum = [0.0]
        cum.reserveCapacity(line.count)
        if line.count > 1 { for i in 1..<line.count { cum.append(cum[i - 1] + distM(line[i - 1], line[i])) } }
        return cum
    }

    struct Proj { var t: Double; var d: Double }

    /// Closest point on segment a-b to p (local equirectangular frame around p).
    static func projSeg(_ p: LatLon, _ a: LatLon, _ b: LatLon) -> Proj {
        let k = cos(p.lat * rad) * rad * earthRadius, m = rad * earthRadius
        let ax = (a.lon - p.lon) * k, ay = (a.lat - p.lat) * m, bx = (b.lon - p.lon) * k, by = (b.lat - p.lat) * m
        let dx = bx - ax, dy = by - ay, l2 = dx * dx + dy * dy
        let t = l2 > 0 ? Swift.max(0, Swift.min(1, -(ax * dx + ay * dy) / l2)) : 0
        let x = ax + t * dx, y = ay + t * dy
        return Proj(t: t, d: hypot(x, y))
    }

    /// One pass of the shape near a stop: segment index, position on it, distance, along-shape meters, point.
    struct Cand { var seg: Int; var t: Double; var d: Double; var pos: Double; var pt: LatLon }
    struct Near { var best: Double; var cands: [Cand] }

    /// Every distinct pass of the line near p: one candidate per run of consecutive segments within
    /// max(60 m, best + 25 m). An out-and-back route yields two candidates for a stop on the shared street.
    static func candidates(_ line: [LatLon], _ cum: [Double], _ p: LatLon) -> Near {
        var segs: [Proj] = []
        var best = Double.infinity
        if line.count > 1 {
            for i in 0..<(line.count - 1) {
                let s = projSeg(p, line[i], line[i + 1])
                segs.append(s)
                if s.d < best { best = s.d }
            }
        }
        let thr = Swift.max(60, best + 25)
        var cands: [Cand] = []
        var run: Cand? = nil
        for (i, s) in segs.enumerated() {
            if s.d > thr { run = nil; continue }
            if run == nil || s.d < run!.d {
                let a = line[i], b = line[i + 1]
                let c = Cand(seg: i, t: s.t, d: s.d, pos: cum[i] + s.t * (cum[i + 1] - cum[i]),
                             pt: LatLon(lat: a.lat + s.t * (b.lat - a.lat), lon: a.lon + s.t * (b.lon - a.lon)))
                if run == nil { cands.append(c) } else { cands[cands.count - 1] = c }
                run = c
            }
        }
        return Near(best: best, cands: cands)
    }

    struct SeqIdx { var ib: Int; var ia: Int; var gap: Int }

    /// Index pair (board, alight) in the stop sequence with the shortest forward gap (wrapping on loops).
    static func seqIndices(_ seq: [String], _ boardId: String, _ alightId: String, _ loop: Bool) -> SeqIdx? {
        let n = seq.count
        var best: SeqIdx? = nil
        for i in 0..<n where seq[i] == boardId {
            var k = 1
            while k < n + (loop ? 0 : -i) {
                let j = loop ? (i + k) % n : i + k
                if j >= n { break }
                if seq[j] == alightId {
                    if best == nil || k < best!.gap { best = SeqIdx(ib: i, ia: j, gap: k) }
                    break
                }
                k += 1
            }
        }
        return best
    }

    /// Pick the candidate nearest an expected along-shape position (circular on closed shapes).
    static func nearestTo(_ cands: [Cand], _ expect: Double, _ L: Double, _ closed: Bool) -> Cand? {
        var best: Cand? = nil
        var bd = Double.infinity
        for c in cands {
            var d = abs(c.pos - expect)
            if closed { d = Swift.min(d, L - d) }
            d += c.d * 0.5   // slight preference for the closer pass when expectations tie
            if d < bd { bd = d; best = c }
        }
        return best
    }

    /// `Array.prototype.slice(from, to)` for non-negative indices (never traps).
    static func jsSlice(_ a: [LatLon], _ from: Int, _ to: Int? = nil) -> [LatLon] {
        let lo = Swift.max(0, Swift.min(from, a.count))
        let hi = Swift.max(lo, Swift.min(to ?? a.count, a.count))
        return Array(a[lo..<hi])
    }

    /// Shape slice from candidate a to candidate b, wrapping through the start on closed shapes.
    static func slice(_ line: [LatLon], _ a: Cand, _ b: Cand, _ closed: Bool) -> [LatLon]? {
        if b.pos > a.pos { return [a.pt] + jsSlice(line, a.seg + 1, b.seg + 1) + [b.pt] }
        if !closed { return nil }
        let last = line.count - 1
        let head = distM(line[0], line[last]) < 5 ? jsSlice(line, 1, b.seg + 1) : jsSlice(line, 0, b.seg + 1)
        return [a.pt] + jsSlice(line, a.seg + 1) + head + [b.pt]
    }

    /// Shortest board-to-alight path over every (board pass, alight pass) pair, or nil.
    static func shortestPass(_ line: [LatLon], _ bCands: [Cand], _ aCands: [Cand], _ closed: Bool,
                             _ b0: LatLon, _ a0: LatLon) -> [LatLon]? {
        var best: [LatLon]? = nil
        var bestL = Double.infinity
        for b in bCands {
            for a in aCands {
                guard let s = slice(line, b, a, closed) else { continue }
                let p = dedupe([b0] + s + [a0]), l = pathLength(p)
                if p.count >= 2 && l < bestL { best = p; bestL = l }
            }
        }
        return best
    }

    static func dedupe(_ pts: [LatLon]) -> [LatLon] {
        var out: [LatLon] = []
        out.reserveCapacity(pts.count)
        for p in pts {
            if let q = out.last, !(abs(q.lat - p.lat) > 1e-7 || abs(q.lon - p.lon) > 1e-7) { continue }
            out.append(p)
        }
        return out
    }

    /// Smallest-distance candidate (first one wins ties, like the web's reduce).
    static func closest(_ cands: [Cand]) -> Cand? {
        guard var m = cands.first else { return nil }
        for c in cands where c.d < m.d { m = c }
        return m
    }

    /// Road-following path for a bus ride: the slice of the route's shape between the boarding and alighting
    /// stops. Out-and-back shapes (one street driven both ways) are disambiguated by the stops' positions in the
    /// route's stop sequence; loop routes (first stop id == last) wrap through the start. A slice far longer
    /// than the fallback is replaced by the shortest pass pair when that one is plausible, else kept (the
    /// route really detours there). Falls back to `fallback` (valid points) only when the stops are not on the
    /// shape (> 200 m) or the ride would go backwards on a non-loop; with no usable fallback, a straight
    /// board-alight line.
    /// - Parameters:
    ///   - shapeLines: shapes[rid]
    ///   - routeStops: routeStops[rid] (first == last means a loop)
    ///   - fallback: usually the stop coordinates from board to alight (`BusLeg.path`)
    public static func alongShape(_ shapeLines: [[LatLon]]?, _ routeStops: [String]?, board: Place, alight: Place,
                                  fallback: [LatLon]? = nil) -> [LatLon] {
        let b0 = board.coord, a0 = alight.coord
        var fb = norm(fallback)
        let realFb = fb.count >= 2
        if !realFb && b0.isValid && a0.isValid { fb = [b0, a0] }
        guard b0.isValid, a0.isValid, let shapeLines else { return fb }

        // pick the shape line that passes closest to both stops (longest wins ties)
        struct Pick { var line: [LatLon]; var cum: [Double]; var cb: Near; var ca: Near; var score: Double }
        var pick: Pick? = nil
        for raw in shapeLines {
            let line = norm(raw)
            if line.count < 2 { continue }
            let cum = cumulative(line)
            let cb = candidates(line, cum, b0), ca = candidates(line, cum, a0)
            let score = cb.best + ca.best
            if let p = pick, !(score < p.score - 1 || (abs(score - p.score) <= 1 && line.count > p.line.count)) { continue }
            pick = Pick(line: line, cum: cum, cb: cb, ca: ca, score: score)
        }
        guard let pk = pick, !(pk.cb.best > maxOffM), !(pk.ca.best > maxOffM) else { return fb }
        let line = pk.line, cb = pk.cb, ca = pk.ca
        let L = pk.cum[pk.cum.count - 1]
        if L <= 0 { return fb }

        var seq = routeStops ?? []
        let loop = seq.count > 2 && seq[0] == seq[seq.count - 1]
        if loop { seq.removeLast() }
        let closed = loop || distM(line[0], line[line.count - 1]) < closedM
        var idx: SeqIdx? = nil
        if let bid = board.id, let aid = alight.id { idx = seqIndices(seq, bid, aid, loop) }

        var cB: Cand? = nil, cA: Cand? = nil
        if let idx {
            let span = Double(loop ? seq.count : Swift.max(1, seq.count - 1))
            // expectations are circular only for loop routes; an out-and-back shape may be geometrically
            // closed but its stop order is linear
            cB = nearestTo(cb.cands, (Double(idx.ib) / span) * L, L, loop)
            if let b = cB {
                let ahead = ca.cands.filter { $0.pos > b.pos }
                let pool = loop ? ca.cands : !ahead.isEmpty ? ahead : closed ? ca.cands : []
                cA = nearestTo(pool, (Double(idx.ia) / span) * L, L, loop)
            }
        } else {
            // unknown sequence: closest pass for boarding, then the first pass ahead of it
            cB = closest(cb.cands)
            if let b = cB {
                let ahead = ca.cands.filter { $0.pos > b.pos }.stableSorted { $0.pos < $1.pos }
                cA = ahead.first ?? (closed ? closest(ca.cands) : nil)
            }
        }
        guard let b = cB, let a = cA, let seg = slice(line, b, a, closed) else { return fb }
        let out = dedupe([b0] + seg + [a0])
        if out.count < 2 { return fb }
        // sanity: a path far longer than the stop-to-stop fallback may mean we picked the wrong pass, so take
        // the shortest pass pair if that one is plausible. If none is, the bus really drives the long way
        // between these stops: keep the shape, never a straight stop-to-stop line.
        if realFb {
            let fl = pathLength(fb), lim = 2.5 * fl + 500
            if fl > 0 && pathLength(out) > lim,
               let alt = shortestPass(line, cb.cands, ca.cands, closed, b0, a0), pathLength(alt) <= lim {
                return alt
            }
        }
        return out
    }
}

extension BusLeg {
    /// The ride as drawn on the map: the route's road shape between the boarding and alighting stops
    /// (`Geometry.alongShape`), the stop-to-stop `path` only when the stops are not on the shape. Same as the
    /// web's map/map.js renderPlan. `path` and `stopIds` stay the stop list (timeline, counts).
    public func roadPath(shapes: [String: [[LatLon]]], routeStops: [String: [String]]) -> [LatLon] {
        Geometry.alongShape(shapes[rid], routeStops[rid], board: board, alight: alight,
                            fallback: path.isEmpty ? [board.coord, alight.coord] : path)
    }
}
